spring:
  # 配置中心地址
  cloud:
    nacos:
      discovery:
        # 开启nacos作为服务注册中心，默认值：true
        enabled: true
        # nacos集群服务注册地址
        server-addr: 192.168.8.142:8848
        # nacos用户名
        username: nacos
        # nacos密码
        password: nacos
        # 命名空间，默认 public,可设置dev,pro等，相同特征的服务分类，先去nacos命名空间创建
        # namespace: public
        # 分组，默认 DEFAULT_GROUP 相同特征的服务划分的更细
        group: DEFAULT_GROUP
        # 临时实例，默认true，false永久实例，即使宕机也不会从nacos服务中删除,可应对雪崩保护，避免服务被删除
        ephemeral: true
        # 权重 1-100 数值越大权重越大分配的流量就越大，通常结合权重负载均衡策略
        weight: 100
#       config:
#         server-addr: ${spring.cloud.nacos.discovery.server-addr}
#         username: ${spring.cloud.nacos.discovery.username}
#         password: ${spring.cloud.nacos.discovery.password}
#         # dataid为yaml的文件扩展名配置方式 ${spring.application.name}.${file‐extension:properties}
#         file-extension: yml
#         # namespace:
#         group: DEFAULT_GROUP
# #        context-path: /nacos
#         # 共享配置
#         #shared-configs:
#         #  - application-${spring.profiles.active}.${spring.cloud.nacos.config.file-extension}


cloud:
  provider:
    group: Nacos 更新