# 应用服务 WEB 访问端口
server:
  port: 8080

# Nacos认证信息
#spring.cloud.nacos.discovery.username=nacos
#spring.cloud.nacos.discovery.password=nacos
# Nacos 服务发现与注册配置，其中子属性 server-addr 指定 Nacos 服务器主机和端口
#spring.cloud.nacos.discovery.server-addr=mse-6d50f4f0-p.nacos-ans.mse.aliyuncs.com:8848
# 注册到 nacos 的指定 namespace，默认为 public
#spring.cloud.nacos.discovery.namespace=public

spring:
  application:
    name: nacos-provider
  cloud:
    nacos:
      config:
        server-addr: 192.168.3.10:8848
        file-extension: yml
      discovery:
        server-addr: 192.168.3.10:8848
        username: nacos
        password: nacos
        metadata:
          gray: true

    sentinel:
      transport:
        dashboard: 192.168.3.10:8948
      #eager: true

  config:
    import:
      - nacos:nacos-provider-dev.yml?refresh=true
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'
logging:
  level:
    com.alibaba.cloud.nacos.configdata: debug
    com.nacos: debug
